### ISSUE TITLE
gradlew not found

### ISSUE THREAD

**Issue by jeffallen** [mpl/go4droid#1]
I tried to run this today and got this:

```
$ docker run mpl7/go4droid
docker: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"./gradlew\": stat ./gradlew: no such file or directory": unknown.
ERRO[0000] error waiting for container: context canceled 
```

I logged into the container with `docker run --rm -i -t mpl7/go4droid bash` and there is no gradlew to be found anywhere. :(

**Comment by mpl** [comment]
thanks, i'll have a look.

**Comment by mpl** [comment]
@jeffallen ./gradlew is not provided in the docker image, as it is specific to each gradle project. if the project you want to work on does not already have a ./gradlew, you're supposed to generate it with the 'gradle wrapper' command.

This is exactly what is described in https://github.com/mpl/go4droid#usage-example

**Comment by jeffallen** [comment]
Thanks, sorry I misunderstood how to use it.

I followed the instructions more carefully and got to here instead:

```
Unzipping /home/gopher/.gradle/wrapper/dists/gradle-2.10-bin/baigpnfu14tdk6ztbfwcl8275/gradle-2.10-bin.zip to /home/gopher/.gradle/wrapper/dists/gradle-2.10-bin/baigpnfu14tdk6ztbfwcl8275
Set executable permissions for: /home/gopher/.gradle/wrapper/dists/gradle-2.10-bin/baigpnfu14tdk6ztbfwcl8275/gradle-2.10/bin/gradle
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:hello:gobind FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':hello:gobind'.
> Cannot get property 'classpath' on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7.548 secs
```

This is probably due to golang/go#21594.

**Comment by mpl** [comment]
Yes, I've been seeing that as well since yesterday (when i was rechecking the steps before answering you about gradlew), and I don't know what's wrong yet.

Thanks for the tip about the golang issue!
